# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.4-node-browsers
      
      - image: circleci/postgres:9.3

      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m

    working_directory: ~/encoded

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "versions.cfg" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get install bsdtar
            sudo npm install -g n
            sudo n 6
            sudo pip install -U zc.buildout setuptools
            buildout bootstrap
            bin/buildout -c buildout.cfg

      - save_cache:
          paths:
            - parts/
            - node_modules/
            - eggs/
            - develop-eggs/
            - develop/
            - bin/
            - /usr/local/lib/node_modules
          key: v1-dependencies-{{ checksum "versions.cfg" }}

      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

      - run:
          name: Tests
          command: |
            bin/test -m "not bdd"

      - run:
          name: Browser tests
          command: |
            bin/test -m bdd -v --splinter-webdriver chrome
        

      - store_artifacts:
          path: test-reports
          destination: test-reports
          